#version 460
#extension GL_EXT_ray_tracing : enable
#extension GL_GOOGLE_include_directive : require

layout(binding = 0, set = 0) uniform accelerationStructureEXT topLevelAS;

layout(binding = 1, set = 0, rgba32f) uniform image2D OutputRadianceImage;
layout(binding = 2, set = 0, rgba32f) uniform image2D OutputAlbedoImage;
layout(binding = 3, set = 0, rgba32f) uniform image2D OutputNormalImage;
layout(binding = 4, set = 0, rgba32f) uniform image2D OutputWorldPositionImage;

// Camera Info
layout(binding = 6, set = 0) uniform CameraData 
{
	mat4 viewInverse;
	mat4 projInverse;
	float samples;
	uint frame;
} cam;

// Light
const uint MAX_AREA_LIGHT_NUM = 5;
const uint MAX_RADIUS_LIGHT_NUM = 5;

struct AreaLightData
{
    vec3 beginPos;
    vec3 u;
    vec3 v;
	vec3 color;
	vec3 rayDir;
};

struct RadiusLightData
{
    vec3 centerPos;
	float padding1;
    vec3 color;
	float padding2;
    float radius;
	vec3 padding3;
};

struct UniformLightData
{
    uint areaLightCount;
    AreaLightData areaLightData[MAX_AREA_LIGHT_NUM];
	uint radiusLightCount;
    RadiusLightData radiusLightData[MAX_RADIUS_LIGHT_NUM];
};
layout(binding = 8, set = 0) buffer Lights { UniformLightData datas; } lightDatas;

#define LIGHT_TYPE_AREA 0
#define LIGHT_TYPE_RADIUS 1

struct RayPayload {
	vec3 hitPosition;
	vec3 hitNormal;
	vec3 hitTangent;
	vec3 hitColor;
	vec3 hitSpecularTint;
	float hitRoughness;
	float hitMetallic;
	float hitSpecular;
  
 	bool isHit;
	bool isLight;
};

// PayLoad
layout(location = 0) rayPayloadEXT RayPayload rayPayLoad;
layout(location = 2) rayPayloadEXT bool shadowed;

#include "random.glsl"
#include "brdf_utils.glsl"
void main() 
{
	const uint MAX_RAY_DEPTH = 8;
	const float MIN_RENDER_NOISE_THRESHOLD = 0.005; 
	const int MIN_NUM_RENDER_SAMPLES = 16;

	float tmin = 0.001;
	float tmax = 10000.0;


	vec3 averageOutputRadiance = vec3(0);
	vec3 averageOutputDirectRadiance = vec3(0);
	vec3 averageOutputIndirectRadiance = vec3(0);
	vec3 averageOutputAlbedo = vec3(0);
	vec3 averageOutputNormal = vec3(0);
	vec3 averageOutputWorldPosition = vec3(0);

	// for denoise
	vec3 accumulateVariance = vec3(0.0);
	vec3 accumulateColor = vec3(0.0);

	uint seed = tea(gl_LaunchIDEXT.y * gl_LaunchSizeEXT.x + gl_LaunchIDEXT.x, cam.frame);

	for(int i = 0; i < cam.samples; i++)
	{
		float r1 = rnd(seed);
		float r2 = rnd(seed);

		// Random Sample
		vec4 origin = cam.viewInverse * vec4(0,0,0,1);
		vec2 subpixel_jitter  =  vec2(r1, r2);
		const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + subpixel_jitter;
		const vec2 inUV        = pixelCenter / vec2(gl_LaunchSizeEXT.xy);
		vec2       d           = inUV * 2.0 - 1.0;
		vec4 target = cam.projInverse * vec4(d.x, -d.y, 1, 1) ;
		vec3 direction = normalize((cam.viewInverse*vec4(normalize(target.xyz), 0.0)).xyz) ;

		// Init Tracing
		vec3 tracingAttenuation = vec3(1);

		bool isFirstHit = true;	
		bool isDirectedLight = true;	
		vec3 OutputRadiance = vec3(0);
		vec3 OutputDirectRadiance = vec3(0);
		vec3 OutputIndirectRadiance = vec3(0);
		vec3 OutputAlbedo = vec3(0);
		vec3 OutputNormal = vec3(0);
		vec3 OutputWorldPosition = vec3(0);

		rayPayLoad.isHit = true;
		rayPayLoad.isLight = false;

		for(int j = 0; j < MAX_RAY_DEPTH; j++)
		{	
			traceRayEXT(topLevelAS, gl_RayFlagsOpaqueEXT, 0xff, 0, 0, 0, origin.xyz, tmin, direction, tmax, 0);
			if(rayPayLoad.isHit)
			{
				if(isFirstHit)
				{
					OutputAlbedo = rayPayLoad.hitColor;
					OutputNormal = rayPayLoad.hitNormal;
					OutputWorldPosition = rayPayLoad.hitPosition;
				}

				// 自发光物???
				if(rayPayLoad.isLight)
				{			
					if(isDirectedLight)
					{
						OutputDirectRadiance += tracingAttenuation * rayPayLoad.hitColor;
					}		
					else
					{
						OutputIndirectRadiance += tracingAttenuation * rayPayLoad.hitColor;
					}
					break;
				}
				// 计算光线弹射
				else
				{
					// Context
					vec3 viewDir = -direction;	
					vec3 normal = normalize(rayPayLoad.hitNormal);
					vec3 tangent = normalize(rayPayLoad.hitTangent);
					vec3 bioNormal = normalize(cross(normal, tangent));
					mat3 TBN = mat3(tangent, bioNormal, normal);
					float NdotV = max(0.0, dot(viewDir, normal)); // 防止背面命中时传入负值进BRDF

					origin = vec4(rayPayLoad.hitPosition + 1e-4 * normal, 1);

					// Directed Light
					// pick light
					uint lightsCount = lightDatas.datas.areaLightCount + lightDatas.datas.radiusLightCount;
					uint lightIdx = nrndRange(seed, 0, lightsCount-1);
					float pick_light_PDF = 1.0 / lightsCount;

					uint lightType;
					bool faceToLight = false;
					vec3 lightOri = origin.xyz;
					vec3 lightVec       = vec3(0.0);
					vec3 lightCol       = vec3(0.0);
					// for area light
					vec3 light_RayDir   = vec3(0.0);
					float light_Area    = 0.0;
					// for radius light
					vec3 light_Normal   = vec3(0.0);
					float light_Radius  = 0.0;
					// get light, process light data
					// Area Light
					if (lightIdx < lightDatas.datas.areaLightCount)
					{
						lightType = LIGHT_TYPE_AREA;

						AreaLightData light = lightDatas.datas.areaLightData[lightIdx];		
						lightCol = light.color;
						// random params
						float ru = rnd(seed);
						float rv = rnd(seed);
						lightVec = light.beginPos + light.u * ru + light.v * rv - lightOri;
						faceToLight = dot(lightVec, normal) > 0;
						light_Area = length(light.u) * length(light.v);
						light_RayDir = light.rayDir;
					}
					else {
						lightIdx -= lightDatas.datas.areaLightCount;
						// Radius Light
						if (lightIdx < lightDatas.datas.radiusLightCount)
						{
							lightType = LIGHT_TYPE_RADIUS;

							RadiusLightData light = lightDatas.datas.radiusLightData[lightIdx];
							lightCol = light.color;
							float phi   = rnd(seed) * 2.0 * M_PI;
							float cosTheta = 1.0 - 2.0 * rnd(seed);   // 均匀分布球面的 cosθ
							float sinTheta = sqrt(max(0.0, 1.0 - cosTheta * cosTheta));
							vec3 lightTarget = light.centerPos + 
								light.radius * vec3(sinTheta * cos(phi), sinTheta * sin(phi), cosTheta);
							lightVec = lightTarget - lightOri;
							// 采样点处球面法线（向外）
							light_Normal = normalize(lightTarget - light.centerPos);
							light_Radius = light.radius;
							faceToLight = dot(lightVec, normal) > 0.0;
						}
					}

					float lightDist = length(lightVec);
					vec3 lightDir = lightVec / lightDist;	

					if(faceToLight)
					{
						
						shadowed = true;
						traceRayEXT(topLevelAS, gl_RayFlagsTerminateOnFirstHitEXT | gl_RayFlagsOpaqueEXT | gl_RayFlagsSkipClosestHitShaderEXT, 0xFF,
									0, 0, 1, lightOri, 1e-4, lightDir, lightDist - 1e-4, 2);
						if(!shadowed)
						{	
							float light_PDF;
							// Compute Light PDF
							if (lightType == LIGHT_TYPE_AREA)
							{	
								light_PDF = (lightDist*lightDist) / (max(1e-4, abs(dot(-lightDir, light_RayDir))) * light_Area);
							}
							else if (lightType == LIGHT_TYPE_RADIUS)
							{				
								float cos_theta_y = abs(dot(-lightDir, light_Normal)); // 入射方向与法线的夹角余弦
								float light_PDF = (lightDist * lightDist) / max(1e-6, cos_theta_y * 4.0 * M_PI * light_Radius * light_Radius);
							}

							float cos_theta_i = dot(lightDir, normal);
							// BRDF Context
							float NdotL = dot(lightDir, normal);
							vec3 H_Dir = normalize(lightDir + viewDir);
							float LdotH = dot(lightDir, H_Dir);
							float NdotH = dot(normal, H_Dir);

							// Compute BRDF
							#include "brdf.glsl"

							float brdf_PDF = pdf_ggx(NdotV, NdotH, dot(viewDir, H_Dir), rayPayLoad.hitRoughness);
							//float weight_MIS = light_PDF*light_PDF  / (light_PDF*light_PDF + brdf_PDF*brdf_PDF);
							float weight_MIS = light_PDF  / (light_PDF + brdf_PDF);

							vec3 lightingRadiance = lightCol * tracingAttenuation * BRDF_Final_Attenuation * cos_theta_i * weight_MIS / (light_PDF * pick_light_PDF);
							// Accumulate Color
							if(isDirectedLight)
								OutputDirectRadiance += lightingRadiance;	
							else
								OutputIndirectRadiance += lightingRadiance;
						}
					}

					// Next Sample
					vec3 ggx_normal = normalize(TBN * sample_ggx(rnd2(seed), rayPayLoad.hitRoughness));
					direction = normalize(reflect(direction, ggx_normal));
					if(dot(direction, normal) <= 0) break;

					// BRDF Context
					float NdotL = dot(direction, normal);
					vec3 H_Dir = normalize(direction + viewDir);
					float LdotH = dot(direction, H_Dir);
					float NdotH = dot(normal, H_Dir);

					// Compute BRDF
					#include "brdf.glsl"

					float brdf_PDF = pdf_ggx(NdotV, NdotH, dot(viewDir, H_Dir), rayPayLoad.hitRoughness);
					float light_PDF = 0;
					// Compute Light PDF
					// Pick Rect Light	
					if (lightType == LIGHT_TYPE_AREA)
					{	
						AreaLightData light = lightDatas.datas.areaLightData[lightIdx];	
						vec3 b = lightOri - light.beginPos;
						vec3 e0 = direction;
						float orig_detemenate = dot(cross(e0, light.u), light.v);
						if (!(orig_detemenate == 0))
						{
							float t = dot(cross(b, light.u), light.v) / orig_detemenate;
							float u = dot(cross(e0, light.v), b) / orig_detemenate;
							float v = dot(cross(b, light.u), e0) / orig_detemenate;
							if (u > 0 && v > 0 && u < 1 && v < 1 && t > 0)
							{
								float dis = length(light.beginPos + light.u * u + light.v * v - lightOri);
								light_PDF = (dis*dis) / (max(1e-4, abs(dot(-direction, light.rayDir))) * light_Area);
							}			
						}
					}
					// Pick Radius Light	
					else if (lightType == LIGHT_TYPE_RADIUS)
					{
						RadiusLightData light = lightDatas.datas.radiusLightData[lightIdx];
						vec3 oc = lightOri - light.centerPos;
						float b = dot(oc, direction);
						float c = dot(oc, oc) - light.radius * light.radius;
						float discriminant = b*b - c;
						if (discriminant > 0.0)
						{
							float t = -b - sqrt(discriminant);   // 最近交点
							if (t > 0.0)
							{
								vec3 hitPoint = lightOri + direction * t;
								vec3 lightNormal = normalize(hitPoint - light.centerPos);
								float cos_theta_y = abs(dot(-direction, lightNormal));
								light_PDF = (t * t) / max(1e-6, cos_theta_y * 4.0 * M_PI * light.radius * light.radius);
							}
						}
					}

					//float weight_MIS = brdf_PDF*brdf_PDF / (light_PDF*light_PDF + brdf_PDF*brdf_PDF);
					float weight_MIS = brdf_PDF / (light_PDF + brdf_PDF);
					
					float cos_theta_i = dot(direction, normal);
					tracingAttenuation *= BRDF_Final_Attenuation * cos_theta_i * weight_MIS / brdf_PDF;				
				}

				if(!isFirstHit)
				{
					isDirectedLight = false;
				}
				isFirstHit = false;
			}
			// 光线逸散???
			else
			{
				// float y = direction.y * 0.5 + 0.5;
				// rayPayLoad.color *= mix(vec3(1.0, 1.0, 1.0), vec3(0.5, 0.7, 1.0), y);
				if(isFirstHit)
				{
					OutputDirectRadiance = vec3(0);
					OutputIndirectRadiance = vec3(0);
					OutputAlbedo = vec3(0);
					OutputNormal = normalize(-direction);
					OutputWorldPosition = -OutputNormal * 1e6;
					isFirstHit = false;
				}
				// tracingColor += vec3(0) * tracingAttenuation;
				break;
			}
		}
		
		vec3 tracingColor = OutputDirectRadiance + OutputIndirectRadiance;
		OutputRadiance = tracingColor / max(vec3(1e-2), OutputAlbedo); // 防止albedo=0时出现NaN/极亮firefly

		averageOutputRadiance = i == 0 ? OutputRadiance : (OutputRadiance / (i + 1) + averageOutputRadiance * i / (i + 1));
		averageOutputDirectRadiance = i == 0 ? OutputDirectRadiance : (OutputDirectRadiance / (i + 1) + averageOutputDirectRadiance * i / (i + 1));
		averageOutputIndirectRadiance = i == 0 ? OutputIndirectRadiance : (OutputIndirectRadiance / (i + 1) + averageOutputIndirectRadiance * i / (i + 1));
		averageOutputAlbedo = i == 0 ? OutputAlbedo : (OutputAlbedo / (i + 1) + averageOutputAlbedo * i / (i + 1));
		averageOutputNormal = i == 0 ? OutputNormal : (OutputNormal / (i + 1) + averageOutputNormal * i / (i + 1));
		averageOutputWorldPosition = i == 0 ? OutputWorldPosition : (OutputWorldPosition / (i + 1) + averageOutputWorldPosition * i / (i + 1));
		
		// 自适应采样
		accumulateVariance += vec3(tracingColor.r * tracingColor.r, tracingColor.g * tracingColor.g, tracingColor.b * tracingColor.b);
		accumulateColor += tracingColor;

 		if(i >= MIN_NUM_RENDER_SAMPLES)
		{	
			vec3 averageColor = accumulateColor / (i+1);
			vec3 noiseVec3 = accumulateVariance / (i+1) - averageColor * averageColor; // D(X) = E(X^2) - E(X)^2
			float noise = noiseVec3.r + noiseVec3.g + noiseVec3.b;
			float norm = min(1.0, length(averageColor));
			float normalizeNoise = norm < 1e-6 ? 0 : noise / norm;
			if (normalizeNoise < MIN_RENDER_NOISE_THRESHOLD) break;
		}
	}

	imageStore(OutputRadianceImage, ivec2(gl_LaunchIDEXT.xy), vec4(averageOutputRadiance, 1));
	imageStore(OutputAlbedoImage, ivec2(gl_LaunchIDEXT.xy), vec4(averageOutputAlbedo, 1));
	imageStore(OutputNormalImage, ivec2(gl_LaunchIDEXT.xy), vec4(averageOutputNormal, 1));
	imageStore(OutputWorldPositionImage, ivec2(gl_LaunchIDEXT.xy), vec4(averageOutputWorldPosition, 1));
}

